/* Generated by Together */

package org.jax.mgi.shr.dla.coordloader;

import org.jax.mgi.shr.ioutils.RecordDataInterpreter;
import org.jax.mgi.shr.config.CoordLoadCfg;
import org.jax.mgi.shr.config.ConfigException;

/**
 * An abstract Coordinate Map Interpreter class that gets the configurable
 *     attributes needed by all coordinate loads
 * @has
 *   <UL>
 *   <LI>A configurator
 *   <LI>map collection
 *   <LI>map collection abbreviation
 *   <LI>coordinate map MGIType
 *   <LI>coordinate map type
 *   <LI>coordinate map unit
 *   <LI>coordinate map version
 *   <LI>coordinate map sequence retrieval parameter
 *   </UL>
 * @does
 *   <UL>
 *       gets configurable values needed by all coordinate map interpreters
 *   </UL>
 * @company The Jackson Laboratory
 * @author sc
 * @version 1.0
 */

abstract public class CoordMapInterpreter implements RecordDataInterpreter {
    // configurator
    protected CoordLoadCfg coordCfg;

    // map collection
    protected String mapCollection;
    protected String mapAbbreviation;

    // coordinate map
    //protected String mapCoordMGIType; - will probably use constants
    protected String mapType;
    protected String mapUnits;
    protected String version;
    protected String retrievalParam;

    // coordinate feature
    protected String logicalDB;


    /**
       * constructs a CoordMapInterpreter by getting Configuration values
       * that are common to all Coordinate Maps
       * @assumes Nothing
       * @effects Nothing
       * @param record Nothing
       * @return Nothing
       * @throws ConfigException if error getting configured values
       */
    public CoordMapInterpreter() throws ConfigException {
        coordCfg = new CoordLoadCfg();
        mapCollection = coordCfg.getMapCollectionName();
        mapAbbreviation = coordCfg.getMapCollectionAbbrev();
       // mapCoordMGIType = coordCfg.getMapMGIType(); - will probalby use constants
        mapType = coordCfg.getMapType();
        mapUnits = coordCfg.getMapUnits();
        version = coordCfg.getMapVersion();
        retrievalParam = coordCfg.getSeqRetrievalParam();
        logicalDB = coordCfg.getLogicalDB();
    }

}
