/* Generated by Together */

package org.jax.mgi.shr.dla.seqloader;

import org.jax.mgi.shr.dbutils.dao.SQLStream;

public class DRSeqProcessor extends SeqProcessor {
    //public DRSeqProcessor( MSProcessor ms, SequenceAttributeResolver sar, String createdModifiedBy) {
    //}

    public void processSequence(SequenceInput seqInput) {
    }

    private SequenceDeleter deleter;
}
