/* Generated by Together */

package org.jax.mgi.shr.dla.seqloader;

import org.jax.mgi.shr.dbutils.dao.SQLStream;
import org.jax.mgi.shr.exception.MGIException;

public class IncremSeqProcessor extends SeqProcessor {
    private SeqEventDetector eventDetect;
    private SequenceLookup seqLookup;
    //public IncremSeqProcessor(SeqEventDetector seqEventDetector,
      //                        MSProcessor ms, SequenceAttributeResolver sar,
        //                      SQLStream sqlStream) {
    //}

    public void processSequence(SequenceInput seqInput) throws MGIException {

    }


}
