/* Generated by Together */

package org.jax.mgi.shr.dla.seqloader;

import org.jax.mgi.dbs.mgd.lookup.PrimarySeqLookup;
import java.util.Vector;
import java.util.Iterator;
import java.util.HashMap;

public class MergeSplitProcessor {
    public MergeSplitProcessor(String logicalDB) {
    }

    public void preProcess(SequenceInput seqInput) {
    }

    public void process() {
    }

    private void addToSet(String primarySeqid, Vector secondarySeqids) {
    }

    private MergeSplitHelper mergeSplitHelper;
    private HashMap mergeSplitSeqs;
}
