/* Generated by Together */

package org.jax.mgi.shr.dla.seqloader;

import org.jax.mgi.dbs.mgd.lookup.PrimarySeqLookup;
import java.util.Set;
public class SeqEventDetector {
    public SeqEventDetector(MergeSplitProcessor mergeSplitProcessor) {
    }

    public String detectEvent(SequenceInput seqInput, Sequence sequence) {
	return null;
    }

    private int logicalDB;
    private PrimarySeqLookup lookup;
    private MergeSplitProcessor eventDetector;
    private Set seqIdsAlreadyAdded;
}
