/* Generated by Together */

package org.jax.mgi.shr.dla.seqloader;

import org.jax.mgi.shr.dbutils.dao.SQLStream;
import org.jax.mgi.shr.dla.seqloader.SequenceAttributeResolver;
import org.jax.mgi.shr.dla.seqloader.AccAttributeResolver;
import org.jax.mgi.shr.dla.seqloader.SeqRefAssocProcessor;
import org.jax.mgi.shr.exception.MGIException;
import java.util.Vector;

abstract public class SeqProcessor  {
    //public SeqProcessor(MSProcessor msProcessor, SequenceAttributeResolver seqAttribResolver) {
    //}

    public abstract void processSequence(SequenceInput sequenceInput)
        throws MGIException;

    //private MSProcessor msProcessor;
    private SequenceAttributeResolver seqAttribResolver;
    private AccAttributeResolver accAttrRes;
    private SeqRefAssocProcessor refAssocProc;
    private Sequence Sequence;
    private SQLStream sqlStream;
    private int compareString;
}
