/* Generated by Together */

package org.jax.mgi.shr.dla.seqloader;

import org.jax.mgi.shr.dbutils.dao.SQLStream;

public class SequenceDeleter {
    public void delete(String createdModifiedBy) {
    }

    private SQLStream sqlStream;
    private String createdModifiedBy;
}
