/* Generated by Together */

package org.jax.mgi.shr.dla.seqloader;

//import org.jax.mgi.dbs.mgd.dao.SequenceState;
public class SequenceUpdater {
   /*
    public boolean updateSeq(SequenceState updateTo, SequenceState updateFrom) {
	return true;
    }
    */
}
